version: '3'

services:
  app:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    env_file:
    - .env.local
    environment:
      - PORT
      - NODE_ENV
      - VUE_APP_MATOMO_URL
      - VUE_APP_MATOMO_SITE
      - VUE_APP_TITLE
    restart: always
    ports:
      - 8080:3000
